### PR TITLE
CRB-135 Remove Deprecation Warnings

### PR DESCRIPTION
**Pull request by seandeneen-gluwa**
This wraps the Source Address' ScriptPubKey into a TxOut object to match NBitcoin's updated API.

### CODE REVIEW

**Comment by atodorov** [comment]
I see the following error in CI: 

`The format of the analysis property sonar.login= is invalid` and I think `secrets.SONAR_TOKEN` isn't configured for this repository. CC @will-gluwa. Without this information I can't say whether or not everything looks good b/c I'm not sure where the obsolete warning was coming from initially. 

FTR I don't like having the special "Merge commit". IMO it's more clean if we rebase PRs before they get merged.

**Comment by CAGS295** [comment]
~~Does this belong to the new [Creditcoin-Shared](https://github.com/gluwa/Creditcoin-Shared/tree/dev/plugins/bitcoin)?~~

**Comment by ghost** [comment]
> I see the following error in CI:
> 
> `The format of the analysis property sonar.login= is invalid` and I think `secrets.SONAR_TOKEN` isn't configured for this repository. CC @will-gluwa. Without this information I can't say whether or not everything looks good b/c I'm not sure where the obsolete warning was coming from initially.

It's because the PR is based on a fork @seandeneen-gluwa made on his account, and his fork doesn't have that secret set.

https://community.sonarsource.com/t/secrets-sonar-token-not-read-when-accessed-from-pr/21269/4

**Comment by atodorov** [comment]
> It's because the PR is based on a fork @seandeneen-gluwa made on his account, and his fork doesn't have that secret set.

I see. In fact it's not that. GitHub isn't exposing secrets for pull requests opened from a fork. 

@seandeneen-gluwa can you open this PR from a branch on the same repository so we can see the CI job executing without errors.

**Comment by seandeneen-gluwa** [comment]
I'm closing this for now to use the branch I pushed to this remote.

**Pull request closed without merging**
